#!/bin/bash
#
#

# filesystem, navigation, terminal
alias back='cd -'                               # go back one folder
alias path='echo $PATH | tr ":" "\n" | sort'    # print $path nicely
alias ls='ls -1AGThl'                           # default format for ls
alias ll='ls -1AGThl'                           # make l also work for ls
alias ..='cd ..'                                # make .. go up a folder
alias clr='clear;echo "Currently logged in on $(tty), as $(whoami) in directory $(pwd)."'
alias cls='clr'                                 # clean screen

# helpers (defaults)
alias grep='grep --color=auto'                  # color grep matches
alias count='wc -l'                             # count lines
alias size='du -sh'                             # get folder size
alias sizer='du -h -c'                          # get and print folder size for all folders, recursively
alias disks='df -H -l'                          # show available disk space
alias ip='ifconfig | grep "inet "'              # quickly print ip address
alias ping='ping -c 5'                          # pings with 5 packets, not unlimited
alias lsp='sudo lsof -i -n -P | grep LISTEN'

# subl
alias code='open -a /Applications/Visual\ Studio\ Code.app/'

# text formatting, copy/paste
alias quickdiff='diff --side-by-side --suppress-common-lines -W 150'
