#!/bin/bash
#
#

# git editor
#export EDITOR="subl -w"



# jvm
#export PATH="$PATH:/Users/Tim/androidsdk/platform-tools:/Users/Tim/androidsdk/tools"

#node
export PATH="$HOME/bin:$PATH" 

#mysql
export PATH="$PATH:/usr/local/mysql/bin/"
